BEER_OBOLON_PREMIUM_EXTRA_1_1_L = 'Пиво "Оболонь Премиум Экстра 1,1 л"'
VODKA_HETMAN_ICE_07_L = 'Водка "Гетьман ICE 0,7 л"'
COFFEE_AROMA_GOLD_CLASSIC_100_GR = 'Кофе "Арома Голд Классик 100 гр"'
APPLE_GOLDEN = 'Яблоко Голден, 1 кг'
COCA_COLA_2_L = 'Напиток Coca Cola 2 л'
SIROK_PLAVLENIY_KOMO_PAPRIKASH = 'Сырок плавленный КОМО Паприкаш'
GARLIK = 'Чеснок'
KENT_8 = 'Сигареты Кент 8'
TEA_MINUTKA_40_BAGS = 'Чай "Минутка" черный 40 пакетиков'
SUN_OIL_SHEDRIY_DAR_RAFINIR_580_GR = 'Масло подсолнечное "Щедрый Дар" 850 г рафинированное'
ONION = 'Лук, 1 кг'
FAIRY_LIMON_500_GR = 'Средство для мытья посуды Fairy, лимон, 500 г'
APPLE_BLACK_PRINCE = 'Яблоко "Черный принц"'
MUSTARD_KOLOS = 'Горчица "Колос"'
SMETANA_STOLICA_SMAKY_20PER_400_GR = 'Сметана "Столица Смаку" 20% 400 гр'
LEMON = 'Лимон, 1 кг'
SUN_OIL_OLEYNA_NERAF_850_GR = 'Масло подсолнечное нерафинированное Олейна, 850 гр'
BEER_LVIVSKE_SVITLE_2_4_L = 'Пиво Львовское светлое 2.4 литра'
SHAVING_FOAM_ARKO_COOL_200_MLG = 'Пена для бритья "Arko Cool 200 млг + бонус 100 млг"'
SHAVING_FOAM_ARKO_SENSITIVE_200_MLG = 'Пена для бритья "Arko Sensitive 200 млг + бонус 100 млг"'
CARROT = 'Морковь, 1 кг'
DROJJI_HARKOV_100_GR = 'Дрожжи харьковские 100 гр хлебо-пекарские пресованные'
EGGS ='Яйца куринные, 10 штук'
DESODORANT_GARNIER_MAGNIY_MEN = 'Дезодорант Garnier Магний для мужчин'
CABBAGE = 'Капуста белокачанная , 1 кг'
MARLBORO_RED = 'Сигареты Marlboro Red'
MAYONES_DETSKIY_SHEDRO_67 = 'Майонез детский Щедро домашний 67% жирности'
DESODORANT_REXONA_ALOE_VERA_WOMEN = 'Дезодорант Rexona Aloe Vera женский'
SMETANA_STOLICA_SMAKY_15_400_GR = 'Сметана Столица Смаку 15% жирности 400 гр'
TEA_MONOMAH_KENYA_BLACK_90_GR = 'Чай Мономах Кения черный 90 гр'
TOILET_PAPER_KIEV_63_M = 'Туалетная бумага Киев 63 м'
TEA_MONOMAH_CEYLON_BLACK = 'Чай Мономах Цейлон черный'
COFFEE_AROMA_GOLD_FREEZE_FRIED_70_GR = 'Кофе Арома Голд Freeze Dried 70 грамм'
MUSTARD_VERES_UKRAINSKA_MICNA_120_GR = 'Горчица Верес украинска мицна 120 грамм'
TEA_MONOMAH_100_CEYLON_ORIGINAL_BLACK_KRUPNOLIST = 'Чай Мономах 100% Цейлон Original черный крупнолистовой'
DESODORANT_GARNIER_VESENNYA_SVEJEST = 'Дезодорант Garnier весенняя свежесть'
APPLE_GALA = 'Яблоко Гала, кг'
SMETANA_GALICHANSKAYA_15_370_GR = 'Сметана Галичанская 15% 370 грамм'
CHIPS_SALT_BIG_PACK_30_GR = 'Чипсы Lays с солью большая пачка 30 грамм'
SPRITE_2L = 'Напиток Sprite 2 литра'
FANTA_2L = 'Напиток Fanta 2 литра'
BOND_STREET_BLUE_SELECTION = 'Сигареты Bond Street Blue Selection'
CAMEL_BLUE = 'Сигареты Camel Blue'
LD_RED = 'Сигареты LD Red'
MARLBORO_GOLD = 'Сигареты Marlboro Gold'
ROTHMANS_DEMI_BLUE_EXCLUSIVE = 'Сигареты Rothmans Demi BLue Exclusive'
ROTHMANS_DEMI_CLICK_PURPLE = 'Сигареты Rothmans Demi Click Purple'
WINSTON_CASTER = 'Сигареты Winston Caster'
PARLAMENT_AQUA_BLUE = 'Сигареты Parlament Aqua Blue'
WINSTON_BLUE = 'Сигареты Winston Blue'
BOND_STREET_RED_SELECTION = 'Сигареты Bond Street Red Selection'
LD_BLUE = 'Сигареты LD Blue'
KENT_SILVER = 'Сигареты Kent Silver'
KENT_NAVY_BLUE_NEW = 'Kent Navy Blue New'
BEER_CHERNIGOVSKOE_SVITLE_05_L_GLASS = 'Пиво "Черниговское Светлое" 0,5 л в стекле'
BEER_STELLA_ARTOIS_05_L_GLASS = 'Пиво "Stella Artois" 0,5 л в стекле'
BEER_OBOLON_SVITLE_05_L_GLASS = 'Пиво "Оболонь Светлое" 0,5 л в стекле'
BEER_JIGULIVSKE_SVITLE_05_L_GLASS = 'Пиво Жигулевское светлое 0,5 л в стекле'
BEER_ROGAN_TRADICIYNE_SVITLE_05_L_GLASS = 'Пиво Рогань традиционное светлое 0,5 л в стекле'
BEER_CORONA_EXTRA_SVITLE_033_L_GLASS = 'Пиво Корона Экстра светлое 0,33 л в стекле'
BEER_CHERNIGIVSKE_BILE_NEFILTER_05_L_GLASS = 'Пиво Черниговоское Белое нефильтрованное 0,5 л в стекле'
BEER_YANTAR_SVITLE_05_L_GLASS = 'Пиво Янтарь светлое 0,5 л в стекле'
BEER_ZIBERT_SVITLE_05_L_GLASS = 'Пиво Zibert светлое 0,5 л в стекле'
BEER_ARSENAL_MICNE_05_L_GLASS = 'Пиво Арсенал мицне 0,5 л в стекле'
BEER_PPB_ZAKARPATSKE_05_L_GLASS = 'Пиво Перша Броварня Закарпатське 0,5 л в стекле'
BEER_LVIVSKE_SVITLE_05_L_GLASS = 'Пиво Львовское светлое 0,5 л в стекле'
BEER_LVIVSKE_1715_05_L_GLASS = 'Пиво Львовское 1715 0,5 л в стекле'
BEER_ZLATA_PRAHA_SVITLE_05_L_GLASS = 'Пиво Zlata Praha светлое 0,5 л в стекле'
BEER_TUBORG_GREEN_05_L_GLASS = 'Пиво Tuborg Green 0,5 л в стекле'
BEER_SLAVUTICH_ICE_MIX_LIME_05_L_GLASS = 'Пиво Славутич ICE MIX Lime 0,5 л в стекле'
BEER_TETEREV_05_L_GLASS = 'Пиво Тетерев 0,5 л в стекле'
BEER_KRUSOVICE_SVITLE_05_L_GLASS = 'Пиво Krusovice светлое 0,5 л в стекле'
BEER_HEINEKEN_SVITLE_05_L_GLASS = 'Пиво Heineken светлое 0,5 л в стекле'
BEER_AMSTEL_SVITLE_05_L_GLASS = 'Пиво Amstel светлое 0,5 л в стекле'
BEER_HIKE_PREMIUM_SVITLE_05_L_GLASS = 'Пиво Hike premium светлое 0,5 л в стекле'
BEER_BOCHKOVE_SVITLE_05_L_GLASS = 'Пиво Бочкове светлое 0,5 л в стекле'
BEER_KRONENBOURG_1664_BLANC_SVITLE_05_L_GLASS = 'Пиво Kronenbourg 1664 Blanc светлое 0,5 л в стекле'
BEER_OPILLYA_FIRMENNOE_SVITLE_05_L_GLASS = 'Пиво Опилля Фирменное непастеризоване светлое 0,5 л в стекле'
BEER_YACHMENNIY_KOLOS_SVITLE_05_L_GLASS = 'Пиво Ячменный Колос светлое 0,5 л в стекле'
BEER_OPILLYA_KORIFEY_SVITLE_05_L_GLASS = 'Пиво "Опилля Корифей" светлое 0,5 в стекле'
BEER_CHAYKA_DNIPROVSKAYA_05_L_GLASS = 'Пиво "Чайка Днепровская" 0,5 л в стекле'
BEER_CHAYKA_CHERNOMORSKAYA_SVITLE_05_L_GLASS = 'Пиво "Чайка Черноморская" светлое 0,5 л в стекле'
BEER_UMAN_WAISSBURG_SVITLE_1_L = 'Пиво Умань Waissburg светлое 1 литр'
BEER_UMAN_PSHENICHNOE_SVITLE_1_L = 'Пиво Умань Пшеничное светлое 1 литр'
BEER_BERDICHEVSKOE_HMELNOE_SVITLE_1_L = 'Пиво Бердичевское Хмельное светлое 1 литр'
BEER_BERDICHEVSKOE_LAGER_SVITLE_1_L = 'Пиво Бердичевское Лагер светлое 1 литр'
BEER_OPILLYA_KORIFEY_11_L = 'Пиво Опилля Корифей 1.1 литра'
BEER_OBOLON_JIGULIVSKE_EXPORTNE_15_L = 'Пиво Оболонь жигулевское экспортное 1.5 литра'
BEER_YANTAR_SVITLE_12_L = 'Пиво Янтарь светлое 1,2 литра'
BEER_JASHKOVSKOE_PSHENICHNOE_NEFILTER_1_L = 'Пиво Жашковское пшеничное нефильтрованное 1 литр'
BEER_JASHKOVSKOE_SVITLE_NEFILTER_1_L = 'Пиво Жашковское светлое нефильтрованное 1 литр'
BEER_JASHKOVSKOE_JIGULIVSKE_NEFILTER_1_L = 'Пиво Жашковское жигулевское нефильтрованное 1 литр'
BEER_PPB_BOCHKOVE_1_L = 'Пиво Перша приватна броварня бочкове 1 литр'
BEER_CHAYKA_DNIPROVSKAYA_1_L = 'Пиво Чайка днипровська 1 литр'
KETCHUP_TORCHIN_CHESNOK_270_GR = 'Кетчуп Торчин с чесноком 270 гр'
MAYONES_KOROLIVSKIY_SMAK_KOROLIVSKIY_67_300_GR = 'Майонез Королевский Смак королевский 67 % 300 гр'
MUKA_ZOLOTE_ZERNYATKO_PSHENICHNE_2_KG = 'Мука ЗОЛОТЕ ЗЕРНЯТКО пшеничное 2 кг'
BEER_CHERNIGOVSKOE_BELOE_NEFILTER_1_L = 'Пиво Черниговское Белое нефильтрованное 1 л'
BEER_OBOLON_SVITLE_1_L = 'Пиво Оболонь светлое 1 л'
BEER_ROGAN_TRADICIYNE_SVITLE_1_L = 'Пиво Рогань традиционное светлое 1 л'
SOUS_CHUMAK_CHESNOCHNIY_200_GR = 'Соус Чумак чесночный 200 грамм'
ORBIT_POLYNICA_BANAN = 'Жвачка Orbit полуниця-банан'
LM_RED = 'Сигареты LM красные'
BEER_JIGULIVSKE_SVITLE_2_L = 'Жигулевское светлое 2 литра'
BEER_CHAYKA_DNIPROVSKAYA_2_L = 'Пиво Чайка Днепровская 2 литра'
BEER_PIWNY_KEBEK_2_L = 'Пиво Piwny Kebek 2 литра'
KETCHUP_TORCHIN_DO_SHASHLIKY_270_GR = 'Кетчуп Торчин до шашлику 270 грамм'
MAYONES_CHUMAK_APPETITNIY_50_300_GR = 'Майонез Чумак аппетитный 50% 300 грамм'
KOLBASA_PERSHA_STOLICA_SALYAMI_FIRMENNAYA_VS = 'Колбаса Перша Столиця Салями Фирменная высший сорт'
COFFEE_CHERNA_KARTA_GOLD_50_GR = 'Кофе Чорна Карта GOLD 50 грамм'
BEER_ARSENAL_MICNE_SVITLE_2_L = 'Пиво Арсенал "Міцне" світле, 2л'
BEER_PPB_BOCHKOVE_SVITLE_2_L = 'Пиво "ППБ Бочкове" світле, 2л'
BEER_PPB_ZAKARPATSKE_ORIGINALNE_SVITLE_2_L = 'Пиво "ППБ Закарпатське оригінальне" світле, 2л'
BEER_ZIBERT_SVITLE_05_L_JB = 'Пиво Zibert светлое 0,5 л в банке'
YOGURT_FANNI_240_GR_1_5_LESNIE_YAGODI = 'Йогурт Фанни 240 грамм 1.5% лесовые ягоды'
KEFIR_SLAVIYA_2_5_850_GR = 'Кефир Славия 2,5% 850 грамм'
BEER_OBOLON_KIEVSKOE_ROZLIVNOE_SVITLE_195_L = 'Пиво Оболонь Киевское розливное светлое 1,95 литра в пластике'
BEER_CHERNIGOVSKOE_LIGHT_SVITLE_2_L = 'Пиво Черниговское light светлое 2,0 л в пластике'
BEER_OPILLYA_KORIFEY_2_L = 'Пиво Опилля Корифей светлое 2,0 л в пластике'
BEER_YANTAR_SVITLE_2_L = 'Пиво Янтарь светлое 2,0 л в пластике'
BEER_TUBORG_GREEN_4_X_05_L = 'Пиво Tuborg Green 4 банки х 0,5 л'
BEER_PPB_ZAKARPATSKE_4_X_05_L = 'Пиво ППБ Закарпатське 4 банки х 0,5 л'
BEER_PPB_BOCHKOVE_4_X_05_L ='Пиво ППБ Бочкове 4 банки х 0,5 л'
BEER_BUDWEISER_BUDVAR_SVITLE_05_L_GLASS = 'Пиво Budweiser Budvar светлое 0,5 л в стекле'
BEER_PILSNER_URQUELL_SVITLE_05_L_GLASS = 'Пиво Pilsner Urquell светлое 0,5 л в стекле'
BEER_ROBERT_DOMS_BELGIYSKIY_SVITLE_NEFILTER_05_L_GLASS = 'Пиво Robert Doms бельгийский светлое нефильтрованное 0,5 л в стекле'
BEER_CHERNIGOVSKOE_SVITLE_05_L_JB = 'Пиво Чернігівське світле 0,5 л жб'
BEER_CHERNIGOVSKOE_BELOE_05_L_JB = 'Пивo Чepнігівськe Білe 0,5 л жб'
BEER_VELKOPOPOVICKY_KOZEL_TEMNE_05_L_JB = 'Пиво Velkopopovicky Kozel темне 0,5 л жб'
BEER_EDELMEISTER_PILSNER_SVITLE_05_L_JB = 'Пиво Edelmeister Pilsner світле фільтроване 0,5 л жб'
BEER_FAXE_SVITLE_05_L_JB = 'Пиво Faxe світле фільтроване 0,5 л жб'
BEER_LIVU_PILZENES_SVITLE_05_L_JB = 'Пиво Livu Pilzenes світле фільтроване 0,5л жб'
BEER_VELKOPOPOVICKY_KOZEL_SVITLE_05_L_JB = 'Пиво Velkopopovicky Kozel світле 0,5л жб'
BEER_OBOLON_BEERMIX_LIMON_05_L_JB = 'Пиво Оболонь BeerMix Лимон 0,5л жб'
BEER_EDELMEISTER_WEIZENBIER_SVITLE_NEFILTER_05_L_JB = 'Пиво Edelmeister Weizenbier світле нефільтроване 0,5 л жб'
BEER_EDELMEISTER_SCHWARZBIER_TEMNE_05_L_JB = 'Пиво Edelmeister Schwarzbier темне фільтроване 0,5 л жб'
BEER_HIKE_BLANCHE_SVITLE_NEFILTER_05_L_JB = 'Пивo Hike Blanche світлe нeфільтpoвaнe 0,5л жб'
BEER_ZLATA_PRAHA_SVITLE_05_L_JB = 'Пиво Zlata Praha світле 0,5л жб'
BEER_THURINGER_PREMIUM_BEER_SVITLE_05_L_JB = 'Пиво Thuringer Premium Beer світле фільтроване 0,5л жб'
BEER_LIVU_SENCU_SVITLE_05_L_JB = 'Пиво Livu Sencu світле фільтроване 0,5л жб'
BEER_GERMANARICH_SVITLE_05_L_JB = 'Пиво Germanarich светлое 0,5 л жб'
BEER_HIKE_PREMIUM_SVITLE_05_L_JB = 'Пиво Hike Преміум світле 0,5л жб'
BEER_OBOLON_0_NONALCO_NEFILTER_SVITLE_05_L_JB = 'Пивo бeзaлкoгoльнe 0,5 л Обoлoнь 0 світлe нефільтроване пaстepизoвaнe жб'
BEER_ZIBERT_BAVARSKOE_SVITLE_05_L_JB = 'Пивo Zibert Баварское светлое 0,5 л жб'
BEER_BAVARIYA_LIQUID_APPLE_NONALCO_SVITLE_05_L_JB = 'Пивo Bavaria Liquid Apple безалкогольное светлое 0,5 л жб'
BEER_HEINEKEN_SVITLE_05_L_JB = 'Пивo Heineken светлое 0,5 л жб'
BEER_RYCHTAR_GRANT_11_SVITLE_05_L_JB = 'Пивo Rychtar Grant 11 светлое 0,5 л жб'
BEER_AMSTEL_SVITLE_05_L_JB = 'Пивo Amstel светлое 0,5 л жб'
BEER_BAVARIA_SVITLE_05_L_JB = 'Пивo Bavaria светлое 0,5 л жб'
BEER_BAVARIA_SVITLE_NONALCO_05_L_JB = 'Пивo Bavaria светлое безалкогольное 0,5 л жб'
BEER_EDELBURG_LAGER_SVITLE_05_L_JB = 'Пиво Edelburg Lager світле 5,2% 0,5 л жб'
BEER_DONNER_PILS_SVITLE_05_L_JB = 'Пиво Donner Pils світле 3,5% 0,5 л жб'
BEER_DUTCH_WINDMILL_SVITLE_05_L_JB = 'Пиво Dutch Windmill світле 4,6% 0,5 л жб'
BEER_EDELBURG_HEFEWEIZEN_SVITLE_NEFILTER_05_L_JB = 'Пиво Edelburg Hefeweizen світле нефільтроване 5,1% 0,5 л жб'
BEER_EDELMEISTER_UNFILTERED_SVITLE_NEFILTER_05_L_JB = 'Пиво Edelmeister Unfiltered світле нефільтроване 5,7% 0,5 л жб'
BEER_ESTRELLA_DAMM_BARCELONA_SVITLE_05_L_JB = 'Пиво Estrella Damm Barcelona світле 4,6% 0,5 л жб'
BEER_HALNE_JASNE_PELNE_05_L_JB = 'Пиво Halne Jasne Pelne з/б 6% 0,5 л жб'
BEER_EUROTOUR_HEFEWEISSBIER_SVITLE_05_L_JB = 'Пиво Eurotour Hefeweissbier світле 5% 0,5л жб'
BEER_HOLLANDIA_STRONG_SVITLE_05_L_JB = 'Пиво Hollandia Strong світле 7,5% 0,5 л жб'
BEER_LANDER_BRAU_PREMIUM_SVITLE_05_L_JB = 'Пиво Lander Brau Premium світле 4,9% 0,5 л жб'
BEER_SAKU_KULD_05_L_JB = 'Пиво Saku Kuld 5,2% 0,5 л жб'
BEER_SAKU_ORIGINAAL_05_L_JB = 'Пиво Saku Originaal 4,7% 0,5 л л жб'
BEER_STANGEN_LAGER_SVITLE_05_L_JB = 'Пиво Stangen Lager світле 5,4% 0,5 л л жб'
BEER_VAN_PUR_PREMIUM_SVITLE_05_L_JB = 'Пиво Van Pur Premium світле 5% 0,5 л жб'
BEER_BAVARIA_MANGO_MARAKUYA_SVITLE_NONALCO_05_L_JB = 'Пиво Bavaria манго-маракуйя світле безалкогольне 0,5 л жб'
BEER_BAVARIA_GRANAT_NONALCO_05_L_JB = 'Пиво Bavaria Гранат безалкогольне 0,5 л жб'
BEER_OBOLON_BEERMIX_MALINA_SVITLE_05_L_JB = 'Пиво Оболонь Beermix Малина світле 2,5% 0,5 л жб'
BEER_OBOLON_BEERMIX_VISHNYA_SPECIALNE_SVITLE_05_L_JB = 'Пиво Оболонь Beermix Вишня спеціальне світле 2,5% 0,5 л жб'
BEER_LOMZA_SVITLE_05_L_JB = 'Пиво Lomza світле 5,7% 0,5 л жб'
BEER_PADERBORNER_PILSENER_SVITLE_05_L_JB = 'Пиво Paderborner Pilsener світле 4,8% 0,5 л жб'
BEER_PADERBORNER_EXPORT_SVITLE_05_L_JB = 'Пиво Paderborner Export світле 5,5% 0,5 л жб'
BEER_CLAUSTHALER_GRAPEFRUIT_NONALCO_05_L_JB = 'Пиво Clausthaler Grapefruit безалкогольне 0,5 л жб'
BEER_CLAUSTHALER_ORIGINAL_NONALCO_05_L_JB = 'Пиво Clausthaler Original безалкогольне 0,5 л жб'
BEER_CLAUSTHALER_LEMON_NONALCO_05_L_JB = 'Пиво Clausthaler Lemon безалкогольне 0,5 л жб'
BEER_FOREVER_ROCK_N_ROLL_SVITLE_NEFILTER_05_L_JB = 'Пиво Forever Rock & Roll світле нефільтроване 7,5% 0,5 л жб'
BEER_FOREVER_BLACK_QUEEN_TEMNE_NEFILTER_05_L_JB = 'Пиво Forever Black Queen темне нефільтроване 5,5% 0,5 л жб'
BEER_FOREVER_KITE_SAFARI_SVITLE_NEFILTER_05_L_JB = 'Пиво Forever Kite Safari світле нефільтроване 7% 0,5 л жб'
BEER_FOREVER_CRAZY_SVITLE_NEFILTER_05_L_JB = 'Пиво Forever Crazy світле нефільтроване 6,5% 0,5 л жб'
BEER_HIKE_LIGHT_SVITLE_05_L_JB = 'Пиво Hike Light світле 3,5% 0,5 л жб'
BEER_HIKE_ZERO_NONALCO_05_L_JB = 'Пиво Hike Zero безалкогольне 0,5л жб'
BEER_HORN_DISEL_ICE_PILSNER_SVITLE_0568_L_JB = 'Пиво Horn Disel Ice Pilsner світле 4,7% 0,568 л жб'
BEER_HORN_DISEL_ORIGINAL_0568_L_JB = 'Пиво Horn Disel Original 5,3% 0,568 л жб'
BEER_HORN_DISEL_TRADITIONAL_SVITLE_0568_L_JB = 'Пиво Horn Disel Traditional світле 6% 0,568 л жб'
BEER_HORN_PREMIUM_DIESEL_SVITLE_05_L_JB = 'Пиво Horn Premium Diesel світле 5% 0,5 л жб'
BEER_KRUSOVICE_CERNE_TEMNE_05_L_JB = 'Пиво Krusovice Cerne темне 3,8% 0,5 л жб'
BEER_LANDER_BRAU_MICNE_05_L_JB = 'Пиво Lander Brau міцне 4,9% 0,5 л жб'
BEER_LANDER_BRAU_SVITLE_NEFILTER_05_L_JB = 'Пиво Lander Brau світле нефільтроване 4,7% 0,5 л жб'
BEER_PADERBORNER_PILGER_SVITLE_NEFILTER_05_L_JB = 'Пиво Paderborner Pilger світле нефільтроване пастеризоване 5% 0,5 л жб'
BEER_PLATAN_JEDENACTKA_11_SVITLE_05_L_JB = 'Пиво Platan Jedenactka 11 світле 4,6% 0,5 л жб'
BEER_PRAGA_SVITLE_05_L_JB = 'Пиво Praga світле фільтроване 4,7% 0,5 л жб'
BEER_SAKU_ROCK_SVITLE_0568_L_JB = 'Пиво Saku Rock світле 5,3% 0,568 л жб'
BEER_SITNAN_SVITLE_05_L_JB = 'Пиво Sitnan світле 5% 0,5л жб'
BEER_VIENAS_PREMIUM_GOLDEN_SVITLE_0568_L_JB = 'Пиво Vienas Premium Golden світле 5% 0,568 л жб'
BEER_VIENAS_PREMIUM_TRADITIONAL_SVITLE_0568_L_JB = 'Пиво Vienas Premium Traditional світле 5,8% 0,568 л жб'
BEER_VLYNSKI_BROWAR_FOREVER_SWEET_WIT_SVITLE_NEFILTER_05_L_JB = 'Пиво Volynski Browar Forever Sweet Wit пшеничне світле нефільтроване 4,5% 0,5л жб'
BEER_ZAHRINGER_PREMIUM_SVITLE_05_L_JB = 'Пиво Zahringer Преміум світле 0,5 л жб'
BEER_ZAHRINGER_HEFEWEIZEN_SVITLE_05_L_JB = 'Пиво Zahringer Hefeweizen світле 0,5 л ж'
BEER_JASHKOVSKOE_SVITLE_NEFILTER_05_L_JB = 'Пиво Жашківське світле нефільтроване 4,5% 0,5 л жб'
BEER_OBOLON_SVITLE_05_L_JB = 'Пиво Оболонь світле 4,5% 0,5 л жб'
BEER_PUBSTER_SVITLE_05_L_JB = 'Пиво Pubster світле 5% 0,5 л жб'
BEER_CHAYKA_CHERNOMORSKAYA_SVITLE_05_L_JB = 'Пиво ППБ Чайка Чорноморська 4,5% 0,5 л жб'
BEER_PPB_ZAKARPATSKE_ORIGINALNE_SVITLE_05_L_JB = 'Пиво ППБ Закарпатське Оригінальне світле 4,4% 0,5 л жб'
BEER_PPB_BOCHKOVE_NEFILTER_05_L_JB = 'Пиво ППБ Бочкове Нефільтроване з/б 4,8% 0,5 л жб'
BEER_PPB_NEFILTROVANE_SVITLE_NONALCO_05_L_JB = 'Пиво ППБ Нефільтроване світле безалкогольне 0,5 л жб'
BEER_PPB_LIMON_LIME_NONALCO_NEFILTER_05_L_JB = 'Пиво ППБ Лимон-Лайм безалкогольне нефільтроване 0,5 л жб'
BEER_CHAYKA_DNIPROVSKAYA_05_L_JB = 'Пиво Чайка Дніпровська світле фільтроване 4,8% 0,5 л жб'
BEER_BROK_EXPORT_SVITLE_05_L_JB = 'Пиво Brok Export світле 5,2% 0,5 л жб'
BEER_CARLING_SVITLE_05_L_JB = 'Пиво Carling світле фільроване з/б 4% 0.5 л жб'
BEER_KETEN_BRUG_BLANCHE_ELEGANT_05_L_JB = 'Пиво Keten Brug Blanche Elegant 4.8% 0.5 л жб'
BEER_BUDWEISER_NONALCO_05_L_JB = 'Пиво Budweiser безалкогольне 0.5 л жб'
BEER_FELDSCHLOSSCHEN_WHEAT_BEER_SVITLE_NEFILTER_05_L_JB = 'Пиво Feldschlosschen Wheat Beer світле нефільтроване 5% 0.5 л жб'
BEER_TETERIV_HMILNA_VISHNYA_NAPIVTEMNE_05_L_JB = 'Пиво Тетерів Хмільна Вишня напівтемне фільтроване з/б 8% 0.5 л жб'
BEER_GROTWERG_SVITLE_NONALCO_05_L_JB = 'Пиво Grotwerg світле пастеризоване фільтроване безалкогольне 0.5 л жб'
BEER_HOLLAND_IMPORT_SVITLE_05_L_JB = 'Пиво Holland Import світле фільтроване 4.8% 0.5 л жб'
BEER_GOLDEN_CASTLE_EXPORT_SVITLE_05_L_JB = 'Пиво Golden Castle Export світле 4.8% 0.5 л жб'
BEER_5_0_ORIGINAL_CRAFT_BEER_SVITLE_NEFILTER_05_L_JB = 'Пиво 5.0 Original Craft Beer світле нефільтроване 4.1% 0.5 л жб'
BEER_GUINESS_DRAUGHT_TEMNE_044_L_JB = 'Пиво Guinness Draught темне фільтроване 4.1% 0.44 л жб'
BEER_GRIMBERGEN_DOUBLE_AMBREE_NAPIVTEMNE_05_L_JB = 'Пиво Grimbergen Double Ambree напівтемне фільтроване 6.5% 0.5 л жб'
BEER_WARSTEINER_PREMIUM_VERUM_SVITLE_05_L_JB = 'Пиво Warsteiner Premium Verum світле фільтроване 4.8% 0.5 л жб'
BEER_DAB_TEMNE_05_L_JB = 'Пиво DAB темне фільтроване 4.9% 0.5 л жб'
BEER_GRIMBERGEN_BLANCHE_SVITLE_05_L_JB = 'Пиво спеціальне Grimbergen Blanche світле пастеризоване 6% 0.5 л жб'
BEER_KLOSTERKELLER_WEISSBIER_CHINA_SVITLE_NEFILTER_05_L_JB = 'Пиво Klosterkeller Weissbier China світле нефільтроване 5.4% 0.5 л жб'
BEER_KARPACKIE_PILS_SVITLE_05_L_JB = 'Пиво Karpackie Pils світле фільтроване 4% 0.5 л жб'
BEER_5_0_ORIGINAL_PILLS_SVITLE_05_L_JB = 'Пиво 5,0 Original Pills світле фільтроване 5% 0.5 л жб'
BEER_5_0_ORIGINAL_LAGER_SVITLE_05_L_JB = 'Пиво 5,0 Original Lager світле фільтроване 5.4% 0.5 л жб'
BEER_5_0_ORIGINAL_WEISS_BEER_SVITLE__NEFILTER_05_L_JB = 'Пиво 5,0 Original Weiss Beer світле нефільтроване 5% 0.5 л жб'
BEER_FAHNEN_BRAU_SVITLE_05_L_JB = 'Пиво Fahnen Brau світле фільтроване 4.7% 0.5 л жб'
BEER_GOSSER_LIGHT_SVITLE_05_L_JB = 'Пиво Gosser Light світле фільтроване 5.2% 0.5 л жб'
BEER_HOLLANDIA_IMPORT_SVITLE_033_L_JB = 'Пиво Hollandia Import світле фільтроване 4.8% 0.33 л жб'
BEER_HOLSTEN_PILSENER_048_L_JB = 'Пиво Holsten Pilsener 4.7% 0.48 л жб'
BEER_OBOLON_PREMIUM_EXTRA_BREW_SVITLE_05_L_JB = 'Пиво Оболонь Premium Extra Brew світле фільтроване з/б 4.6% 0.5 л жб'
BEER_LVIVSKE_SVITLE_048_L_JB = 'Пиво Львівське світле 4,3% 0,48 л жб'
BEER_CARLSBERG_PREMIUM_PILSNER_SVITLE_05_L_JB = 'Пиво Carlsberg Premium Pilsner світле фільтроване з/б 5% 0.5 л жб'
BEER_CARLSBERG_PILSNER_05_L_JB = 'Пиво Carlsberg Pilsner 0.5 л жб'
BANANA = 'Банан, кг'
ORANGE = 'Апельсин, кг'
KIWI = 'Киви, кг'
COCONUT = 'Кокос'
GRAPEFRUIT = 'Грейпфрут, кг'
POMEGRANATE = 'Гранат, кг'
MANGO = 'Манго'
POTATO = 'Картошка, кг'
TOMATO = 'Помидоры, кг'
CUCUMBER = 'Огурцы, кг'
KABACHKI = 'Кабачки, кг'
RED_BOLG_PAPPER = 'Красный болгарский перец, кг'
YELLOW_BOLG_PAPPER = 'Желтый болгарский перец, кг'
ASPARAGUS = 'Спаржа'
BROCCOLI = 'Брокколи'
CAPTAIN_MORGAN_SPICED_GOLD_1L = 'Напиток ромовый Captain Morgan Spiced Gold 1 литр'
BELLS_ORIGINAL_07L = "Виски Bells's Original 0.7 л"
MARTINI_ASTI_BILE_075L = 'Вино игристое Martini Asti белое 0,75 л'
JAMESON_IRISH_WHISKEY_07L = 'Виски Jameson Irish Whiskey 0.7 л'
BELLS_ORIGINAL_1L = "Виски Bells's Original 1 л"
CAPTAIN_MORGAN_SPICED_GOLD_05L = 'Напиток ромовый Captain Morgan Spiced Gold 0.5 л'
JAMESON_IRISH_WHISKEY_05L = 'Виски Jameson Irish Whiskey 0.5 л'
JW_RED_LABEL_05L = 'Виски Johnie Walker Red Label 0.5 л'
BELLS_SPICED_07L = "Виски Bells's Spiced 0.7 л"
BALLANTINES_FINEST_07L = 'Виски Ballantines Finest 0.7 л'
JACK_DANILES_07L = "Виски Jack Daniel's old N7 tennesi 0.7 л"
JACK_DANILES_1L = "Виски Jack Daniel's old N7 tennesi 1 л"
JIM_BEAM_WHITE_07L = "Бурбон Jim Beam White 0.7 л"
BORJOMI_SILNOGAZ_05L = "Минеральная вода Borjomi сильногазированная 0,5 л"
MORSHINSKAYA_NEGAZ_15L = "Минеральная вода Морщинская негазированная 1,5 л"
MORSHINSKAYA_LOW_GAZ_15L = "Минеральная вода Морщинская слабогазированная 1,5 л"
MORSHINSKAYA_HIGH_GAZ_15L = "Минеральная вода Морщинская сильногазированная 1,5 л"
NASH_SIK_APPLE_GRAPE_02L = 'Нектар Наш Сік яблуко-виноград 200 гр'
NASH_SIK_APPLE_CARROT_02L = 'Сік Наш Сік яблуко-морква 200 гр'
NASH_SIK_ORANGE_02L = 'Нектар Наш Сік апельсин 200 гр'
NASH_SIK_MULTIFRUKT_02L = 'Нектар Наш Сік мультифрукт 200 гр'
NASH_SIK_APPLE_PEACH_02L = 'Сік Наш Сік яблуко-персик 200 гр'
NASH_SIK_PEAR_APPLE_02L = 'Сік Наш Сік груша-яблуко 200 гр'
NASH_SIK_MULTIVITAMIN_02L = 'Сік Наш Сік мультивітамін 200 гр'
NASH_SIK_APPLE_02L = 'Сік Наш Сік яблучний 200 гр'
NASH_SIK_APPLE_STRAWBERRY_02L = 'Сік Наш Сік яблуко-полуниця 200 гр'
NON_STOP_ORIGINAL_025L = 'Енергетичний напій Non Stop Original 250 мл'
NON_STOP_ORIGINAL_05L = 'Енергетичний напій Non Stop Original 500 мл'
NON_STOP_JUNGLE_025L = 'Енергетичний напій Non Stop Jungle 250 мл'
NON_STOP_BOOST_05L = 'Енергетичний напій Non Stop Boost 500 мл'
NON_STOP_ULTRA_05L = 'Енергетичний напій Non Stop Ultra 500 мл'
NON_STOP_BOOST_025L = 'Енергетичний напій Non Stop Boost 250 мл'
BURN_CLASSIC_025L = 'Енергетичний напій Burn Classic 250 мл'
BURN_CLASSIC_05L = 'Енергетичний напій Burn Classic 500 мл'
BURN_MANGO_025L = 'Енергетичний напій Burn Mango 250 мл'
BURN_APPLE_KIWI_05L = 'Енергетичний напій Burn Apple-Kiwi 500 мл'
BURN_DARK_ENERGY_025L = 'Енергетичний напій Burn Dark Energy 250 мл'
RED_BULL_025L = 'Енергетичний напій Red Bull 250 мл'
RED_BULL_0355L = 'Енергетичний напій Red Bull 355 мл'
RED_BULL_0473L = 'Енергетичний напій Red Bull 473 мл'
RED_BULL_0591L = 'Енергетичний напій Red Bull 591 мл'
RED_BULL_SUGAR_FREE_025L = 'Енергетичний напій Red Bull Sugar Free 250 мл'
RED_BULL_RED_EDITION_CAVUN_025L = 'Енергетичний напій Red Bull Red Edition зі смаком кавуна 250 мл'
RED_BULL_YELLOW_EDITION_TROPIC_FRUITS_025L = 'Енергетичний напій Red Bull Yellow Edition зі смаком тропічних фруктів 250 мл'
MONSTER_0355L = 'Енергетичний напій Monster 355 мл'
MONSTER_THE_DOCTOR_0355L = 'Енергетичний напій Monster The Doctor 355 мл'
MONSTER_ULTRA_ZERO_0355L = 'Енергетичний напій Monster Ultra Zero 355 мл'
MONSTER_JUICED_0355L = 'Енергетичний напій Monster Juiced 355 мл'
PIT_BULL_COFFEE_025L = 'Енергетичний напій Pit Bull Coffee 250 мл'
PIT_BULL_POWER_025L = 'Енергетичний напій Pit Bull Power 250 мл'
PIT_BULL_X_025L = 'Енергетичний напій Pit Bull X 250 мл'
PIT_BULL_EXTRA_VITAMIN_C_025L = 'Енергетичний напій Pit Bull Extra Vitamin C 250 мл'
PIT_BULL_025L = 'Енергетичний напій Pit Bull 250 мл'
MACCOFFEE_GOLD_ROZCHIN_SOFT_PACK_60_GR = 'Кава розчинна MacCoffee Gold натуральна д/п, 60г'
NESCAFE_GOLD_ROZCH_SOFT_PACK_120_GR = 'Кава розчинна Nescafe Gold м`яка упаковка, 120г'
GRANO_DORADO_GOLD_SOFT_P_130GR = 'Кава розчинна Grano Dorado Gold, 130г'
NESCAFE_CLASSIC_SOFT_P_60GR = 'Кава розчинна Nescafe Classic, 60г'
CHORNA_CARTA_GOLD_SOFT_P_400GR = 'Кава розчинна Чорна карта GOLD пакет, 400г'
BOUNTY_SMALL = 'Батончик Bounty з м`якоттю кокоса в молочному шоколаді, 57г'
BOUNTY_BIG = 'Батончик Bounty Trio з м`якоттю кокоса в молочному шоколаді, 85г'
MARS_SMALL = 'Батончик Mars з нугою і карамеллю в молочному шоколаді, 51г'
MARS_BIG = 'Батончик Mars нуга/карамель в молочному шоколаді, 70г'
NUTS_STRAWBERRY = 'Батончик Nuts Strawberry, 42 г'
NUTS_SMALL = 'Батончик Nuts шоколадний, 42г'
NUTS_KING_SIZE = 'Батончик Nuts King size шоколадний, 60г'
SNICKERS_SMALL = 'Батончик Snickers з арахісом у молочному шоколаді, 50г'
SNICKERS_SUPER = 'Батончик Snickers Super з арахісом в молочному шоколаді, 112,5г'
SNICKERS_CREAMY_PEANUT_BUTTER = 'Батончик Snickers з арахісовим маслом, 54,75г'
SNICKERS_CREAMY_PEANUT_BUTTER_SMALL = 'Батончик Snickers з арахісовим маслом, 36,5г'
TWIX_PECHIVO_KARAMEL_50GR = 'Батончик Twix з печивом і карамеллю в молочному шоколаді, 50г'
TWIX_EXTRA_PECHIVO_KARAMEL_75GR = 'Батончик Twix Extra печиво-карамель в молочному шоколаді, 75г'
VODKA_ABSOLUT_05L = 'Горілка Absolut, 0,5л'
VODKA_ABSOLUT_1L = 'Горілка Absolut, 1 л'
VODKA_ABSOLUT_07L = 'Горілка Absolut, 0,7л'
VODKA_ABSOLUT_LIME_07L = 'Горілка Absolut Lime, 0,7л'
VODKA_ABSOLUT_GRAPEFRUIT_07L = 'Горілка Absolut Grapefruit, 0,7л'
VODKA_ABSOLUT_ELYX_07L = 'Горілка Absolut Elyx, 0,7л'
VODKA_ABSOLUT_CITRON_07L = 'Горілка Absolut Citron, 0,7л'
VODKA_ABSOLUT_KURANT_07L = 'Горілка Absolut Kurant, 0,7л'
VODKA_ABSOLUT_WATERMELON_07L = 'Горілка Absolut Watermelon, 0,7л'
VODKA_ABSOLUT_MANDARIN_07L = 'Горілка Absolut Mandarin, 0,7л'
VODKA_FINLAND_05L = 'Горілка Finlandia, 0,5л'
VODKA_FINLAND_07L = 'Горілка Finlandia, 0,7л'
VODKA_FINLAND_1L = 'Горілка Finlandia, 1л'
VODKA_FINLAND_REDBERRY_05L = 'Горілка Finlandia Redberry, 0,5л'
VODKA_FINLAND_REDBERRY_1L = 'Горілка Finlandia Redberry, 1 л'
VODKA_FINLAND_CRANBERRY_05L = 'Горілка Finlandia Cranberry, 0,5л'
VODKA_FINLAND_CRANBERRY_1L = 'Горілка Finlandia Cranberry, 1 л'
VODKA_FINLAND_GRAPEFRUIT_05L = 'Горілка Finlandia Grapefruit, 0,5л'
VODKA_FINLAND_LIME_05L = 'Горілка Finlandia Lime, 0,5л'
VODKA_FINLAND_COCONUT_05L = 'Горілка Finlandia Coconut, 0,5л'
VODKA_FINLAND_BLACKCURRANT_05L = 'Горілка Finlandia Blackcurrant, 0,5л'
VODKA_FINLAND_LIME_1L = 'Горілка Finlandia Lime, 1 л'
VODKA_FINLAND_BLACKCURRANT_1L = 'Горілка Finlandia Blackcurrant, 1 л'
VODKA_FINLAND_GRAPEFRUIT_1L = 'Горілка Finlandia Grapefruit, 1 л'
VODKA_FINLAND_WHITE_175L = 'Горілка Finlandia White, 1.75 л'
VODKA_NEMIROFF_DELIKAT_SOFT_05L = "Горілка Nemiroff Delikat м'яка, 0,5л"
VODKA_NEMIROFF_SHTOF_05L = "Горілка Nemiroff Штоф особлива, 0,5л"
VODKA_NEMIROFF_UKR_PSHEN_05L = "Горілка Nemiroff українська пшениця, 0,5л"
VODKA_NEMIROFF_DELUX_05L = "Горілка Nemiroff Де Люкс, 0,5л"
VODKA_NEMIROFF_LEX_05L = "Горілка Nemiroff Lex, 0,5л"
SHAMP_ARTEMIVSKE_BILE_NAPIVSOLOD = "Шампанське АЗШВ Артемівське біле напівсолодке, 0,75л"
SHAMP_ARTEMIVSKE_ROJEVE_NAPIVSUHE = "Шампанське АЗШВ Артемівське рожеве напівсухе, 0,75л"
SHAMP_ARTEMIVSKE_BILE_BRUT = "Шампанське АЗШВ Артемівське біле брют, 0,75л"
SHAMP_ARTEMIVSKE_COLLECT_NAPIVSUHE = "Шампанське АЗШВ Артемівське коллекційне напівсухе, 0,75л"
SHAMP_ARTEMIVSKE_CHERVONE_NAPIVSOLOD = "Шампанське АЗШВ Артемівське червоне напівсолодке, 0,75л"
SHAMP_BAGRATIONI_BILE_NAPIVSOLOD = "Шампанське Bagrationi біле напівсолодке, 0,75л"
SHAMP_BAGRATIONI_BILE_NAPIVSUHE = "Шампанське Bagrationi біле напівсухе, 0,75л"
SHAMP_BAGRATIONI_BILE_BRUT = "Шампанське Bagrationi біле брют, 0,75л"
SHAMP_BAGRATIONI_ROJ_NAPIVSOLOD = "Шампанське Bagrationi рожеве напівсолодке, 0,75л"
SHAMP_BAGRATIONI_GOLD_NAPIVSOLOD = "Шампанське Bagrationi Gold напівсолодке, 0,75л"
SHAMP_BOLGRAD_BILE_BRUT = "Шампанське Bolgrad біле брют, 0,75л"
SHAMP_BOLGRAD_BILE_NAPIVSOLOD = "Шампанське Bolgrad біле напівсолодке, 0,75л"
SHAMP_BOLGRAD_NECTAR_BILE_SOLODKE = "Шампанське Bolgrad Nectar біле солодке, 0,75л"
SHAMP_FRAN_BULV_BILE_NAPIVSUHE = "Шампанське Французький Бульвар біле напівсухе, 0,75л"
SHAMP_FRAN_BULV_BILE_BRUT = "Шампанське Французький Бульвар біле брют, 0,75л"
SHAMP_FRAN_BULV_BILE_NAPIVSOLOD = "Шампанське Французький Бульвар біле напівсолодке, 0,75л"
STARIY_KOHETI_3 = "Коньяк Старий Кахеті 3 зірки, 0,5л"
STARIY_KOHETI_4 = "Коньяк Старий Кахеті 4 зірки, 0,5л"
STARIY_KOHETI_5 = "Коньяк Старий Кахеті 5 зірок, 0,5л"
BRENDI_KOBLEVO_RESERVE_EXTRA_OLD_8_YEARS_05L = "Бренді Коблево Reserve Extra Old 8років, 0,5л"
SHABO_VSOP_5 = "Коньяк 'Шабо VSOP' 5 зірок, 0,5л"
SHABO_VS_3 = "Коньяк 'Шабо VS' 3 зірки, 0,5л"
SHABO_1788_4 = "Коньяк 'Шабо 1788' 4 зірки, 0,5л"
SHABO_1788_RESERV = "Коньяк 'Шабо 1788' резерв, 0,5л"
SHABO_VS_RESERV = "Коньяк 'Шабо VS' резерв, 0,5л"
SHABO_VSOP_RESERV = "Коньяк 'Шабо VSOP' резерв, 0,5л"
AZNAURI_3 = "Коньяк 'Азнаурі' 3 зірки, 0,5л"
AZNAURI_5 = "Коньяк 'Азнаурі' 5 зірок, 0,5л"
AZNAURI_4 = "Коньяк 'Азнаурі' 4 зірки, 0,5л"
AZNAURI_BLACK_BARREL_5 = "Коньяк 'Азнаурі Black Barrel' 5 зірок, 0,5л"
ADJARI_3 = "Коньяк 'Adjari' 3 зірки, 0,5л"
ADJARI_5 = "Коньяк 'Adjari' 5 зірок, 0,5л"
ADJARI_4 = "Коньяк 'Adjari' 4 зірки, 0,5л"
HENNESY_VS = "Коньяк 'Hennesy VS' в подарунковій упаковці, 0,5л"
HENNESY_VSOP = "Коньяк 'Hennesy VSOP' в подарунковій упаковці, 0,5л"
ALEXX_GOLD_VSOP = "Коньяк 'AleXX Gold VSOP' в тубусі, 0,5л"
ALEXX_SILVER_VS = "Коньяк 'AleXX Silver VS' в тубусі, 0,5л"
ARARAT_5 = "Коньяк 'Ararat' 5 зірок, 0,5л"
ARARAT_AHTAMAR_10 = "Коньяк 'Ararat Ahtamar' 10 років, 0,5л"
ARARAT_3 = "Коньяк 'Ararat' 3 зірки, 0,5л"
ARARAT_NAIRI_20 = "Коньяк 'Ararat Nairi' 20 років, 0,5л"
GREEN_DAY_AIR_05L = "Горілка Green Day Air, 0,5л"
GREEN_DAY_ULTRA_SOFT_05L = "Горілка Green Day Ultra Soft 40%, 0,5л"
GREEN_DAY_ORGANIC_LIFE_05L = "Горілка Green Day Organic Life, 0,5л"
GREEN_DAY_CRYSTAL_05L = "Горілка Green Day Crystal 40%, 0,5л"
GREEN_DAY_05L = "Горілка Green Day, 0,5л"
MEDOFF_CLASSIC_05L = "Горілка Medoff Класік New, 0,5л"
SMIRNOFF_RED_05L = "Горілка Smirnoff Red, 0,5л"
KOZACKA_RADA_CLASSIC_05L = 'Горілка Класична "Козацька рада", 0,5л'
KOZACKA_RADA_OSOBLIVA_05L = 'Горілка "Козацька рада" Особлива, 0,5л'
ZUBROWKA_BISON_GRASS_05L = "Горілка Zubrowka Bison Grass, 0,5л"
ZUBROWKA_BIALA_05L = "Горілка Zubrowka Biala, 0,5л"
ZUBROWKA_CZARNA_05L = "Горілка Zubrowka Сzarna, 0,5л"
VOZDUH_LEGKA_05L = "Горілка Воздух Легка особлива, 0,5л"
VOZDUH_ALPHA_05L = "Горілка Повітря Альфа, 0,5л"
PERSHA_GILDIYA_VERHOVNA_05L = 'Горілка "Перша гільдія" Верховна, 0,5л'
PERSHA_GILDIYA_ZNATNA_05L = 'Горілка "Перша гільдія" Знатна, 0,5л'
PERSHA_GILDIYA_POVAJNA_05L = 'Горілка "Перша гільдія" Поважна, 0,5л'
HLIB_DAR_CLASSIC_05L = 'Горілка "Хлібний Дар" Класична, 0,5л'
HLIB_DAR_PROR_ZERNO_05L = 'Горілка "Хлібний Дар" на пророщеному зерні, 0,5л'
HLIB_DAR_JITNYA_05L = 'Горілка "Хлібний Дар" Житня, 0,5л'
HLIB_DAR_PSHENICHNA_05L = 'Горілка "Хлібний Дар" Пшенична, 0,5л'
GREEN_DAY_ORGANIC_LIFE_07L = 'Горілка Green Day Organic Life, 0,7л'
GREEN_DAY_07L = 'Горілка Green Day, 0,7л'
GREEN_DAY_ULTRA_SOFT_07L = 'Горілка Green Day Ultra Soft 40%, 0,7л'
GREEN_DAY_AIR_07L = 'Горілка Green Day Air, 0,7л'
GREEN_DAY_CRYSTAL_07L = 'Горілка Green Day Crystal 40%, 0,7л'
MEDOFF_CLASSIC_07L = "Горілка Medoff Класік, 0,7л"
NEMIROFF_DELIKAT_MYAKA_07L = "Горілка Nemiroff Delikat м`яка, 0,7л"
NEMIROFF_OSOBLIVA_SHTOF_07L = "Горілка Nemiroff Особлива штоф, 0,7л"
NEMIROFF_DELUXE_07L = "Горілка Nemiroff Де Люкс, 0,7л"
NEMIROFF_LEX_07L = "Горілка Nemiroff Lex, 0,7л"
ZUBROWKA_07L = "Горілка Zubrowka, 0,7л"
ZUBROWKA_CZARNA_07L = "Горілка Zubrowka Сzarna, 0,7л"
HETMAN_07L = "Горілка Гетьман, 0,7л"
KOZACKA_RADA_CLASSIC_07L = 'Горілка "Козацька рада" Класична, 0,7л'
KOZACKA_RADA_PREMIUM_07L = 'Горілка "Козацька рада" Преміум, 0,7л'
KOZACKA_RADA_OSOBLIVA_07L = 'Горілка "Козацька рада" Особлива, 0,7л'
PERSHA_GILDIYA_POVAJNA_07L = 'Горілка "Перша гільдія" Поважна, 0,7л'
PERSHA_GILDIYA_VERHOVNA_07L = 'Горілка "Перша гільдія" Верховна, 0,7л'
PERSHA_GILDIYA_ZNATNA_07L = 'Горілка "Перша гільдія" Знатна, 0,7л'
HLIB_DAR_CLASSIC_07L = 'Горілка "Хлібний Дар" Класична, 0,7л'
MEDOFF_CLASSIC_1L = 'Горілка Medoff Класік , 1л'
NEMIROFF_SHTOF_1L = 'Горілка Nemiroff Особлива штоф, 1л'
NEMIROFF_DELICAT_SOFT_1L = 'Горілка Nemiroff Delikat м`яка, 1л'
ZUBROWKA_BISON_GRASS_1L = 'Горілка Zubrowka Bison Grass, 1л'
ZUBROWKA_BIALA_1L = 'Горілка Zubrowka Biala, 1л'
HETMAN_1L = 'Горілка Гетьман, 1000мл'
KOZACKA_RADA_OSOBLIVA_1L = 'Горілка "Козацька рада" Особлива, 1л'
KOZACKA_RADA_CLASSIC_1L = 'Горілка "Козацька рада" Класична, 1л'
HLIB_DAR_CLASSIC_1L = 'Горілка "Хлібний Дар" Класична, 1л'
SVINNE_REBRO = 'Свинне ребро, кг'
SALO = 'Свиняче сало фермерське, кг'
SVINNA_GOMILKA = 'Свинна гомілка, кг'
SVIN_PECHINKA = 'Печінка свинна охолоджена, кг'
SVIN_GULYASH = 'Свинячий гуляш, кг'
SVIN_PIDJARKA = 'Свинна піджарка, кг'
SVIN_KOREYKA = 'Свинна корейка, кг'
SVIN_VIRIZKA = 'Свинна вирізка, кг'
SVIN_LOPATKA_BEZ_KISTKI = 'Свинна лопатка без кістки, кг'
SVIN_OKIST_BEZ_KISTKI = 'Свинний окіст без кістки, кг'
SVIN_FARSH = 'Фарш свинний, кг'
SVIN_BITOK_BEZ_KISTI = 'Свинний биток без кістки, кг'
SVIN_RAGU = 'Свинне рагу, кг'
SVIN_OSHEYEK_BEZ_KISTKI = 'Свинний ошийок без кістки, кг'
KURYACHA_CHETVERT = 'Куряча четвертина, кг'
KURYACHE_STEGNO = 'Куряче стегно, кг'
KURYACHE_KRILO = 'Куряче крило, кг'
KURYACHE_FILE = 'Куряче філе, кг'
KURYACHA_GOMILKA = 'Куряча гомілка, кг'
COCA_COLA_ORIGINAL_033_JB = 'Напій Coca-Cola банка, 0,33л'
COCA_COLA_ZERO_033_JB = 'Напій Coca-Cola Zero м/б, 0,33л'
FANTA_ORANGE_033_JB = 'Напій Fanta Orange м/б, 0,33л'
FANTA_PINEAPPLE_033_JB = 'Напій Fanta Pineapple з/б, 0,355л'
SPRITE_033_JB = 'Напій Sprite м/б, 0,33л'
COCA_COLA_ORIGINAL_025_GLASS = 'Напиток Coca-Cola ст.бут., 0,25л'
COCA_COLA_ZERO_025_GLASS = 'Напиток Coca-Cola Zero стекло, 0,25л'
COCA_COLA_ORIGINAL_05_PL = 'Напиток Coca-Cola 0,5л'
COCA_COLA_ZERO_05_PL = 'Напиток Coca-Cola Zero, 0,5л'
FANTA_ORANGE_05_PL = 'Напиток Fanta Orange 0,5л'
SPRITE_05_PL = 'Напиток Sprite 0,5л'
COCA_COLA_ORIGINAL_15_PL = 'Напиток Coca-Cola Original 1,5л'
COCA_COLA_ZERO_15_PL = 'Напиток Coca-Cola Zero 1.5 л'
SPRITE_15_PL = 'Напиток Sprite 1,5л'
FANTA_ORANGE_15_PL = 'Напиток Fanta Orange 1,5л'
FANTA_SHOKATA_15_PL = 'Напиток Fanta Shokata, 1,5л'
FANTA_MANDARIN_15_PL = 'Напиток Fanta Мандарин, 1,5л'
CHIPS_LUXE_BECON_133GR = 'Чіпси Люкс бекон, 133г'
CHIPS_LUXE_PAPRIKA_133GR = 'Чіпси Люкс паприка, 133г'
CHIPS_LUXE_CRAB_133GR = 'Чіпси Люкс краб, 133г'
CHIPS_LUXE_SMETANA_CIBULYA_133GR = 'Чіпси Люкс сметана-цибуля, 133г'
CHIPS_LUXE_SIR_133GR = 'Чіпси Люкс сир, 133г'
CHIPS_LUXE_SIR_71GR = 'Чіпси Люкс сир, 71г'
CHIPS_LUXE_BECON_71GR = 'Чіпси Люкс бекон, 71г'
CHIPS_LUXE_PAPRIKA_71GR = 'Чіпси Люкс паприка, 71г'
CHIPS_LUXE_CRAB_71GR = 'Чіпси Люкс краб, 71г'
CHIPS_LUXE_SMETANA_CIBULYA_71GR = 'Чіпси Люкс сметана-цибуля, 71г'
CHIPS_LUXE_HVIL_LISICHKI_125GR = 'Чіпси Люкс хвилясті зі смаком лисичок, 125г'
CHIPS_LUXE_SMETANA_CIBULYA_183GR = 'Чіпси Люкс зі смаком сметани та цибулі, 183г'
CHIPS_LUXE_BECON_183GR = 'Чіпси Люкс зі смаком бекону, 183г'
CHIPS_LUXE_SIR_183GR = 'Чіпси Люкс зі смаком сиру, 183г'
CHIPS_PRINGLES_GREECE_SOUCE_CACIKI_185GR = 'Снек пікантний Pringles Грецький соус цацикі, 185г'
CHIPS_PRINGLES_PAPRIKA_165GR = 'Снек пікантний Pringles Паприка, 165г'
CHIPS_PRINGLES_PIZZA_PEPERONI_185GR = 'Снек пікантний Pringles Піца пепероні, 185г'
CHIPS_PRINGLES_SIR_CIBULYA_165GR = 'Чіпси Pringles сир-цибуля, 165г'
CHIPS_PRINGLES_ORIGINAL_165GR = 'Чіпси Pringles Оригінал, 165г'
CHIPS_PRINGLES_SIR_165GR = 'Чіпси Pringles сир, 165г'
CHIPS_LAYS_PAPRIKA_120GR = 'Чипси Lay`s картопляні зі смаком паприки, 120г'
CHIPS_LAYS_CRAB_120GR = 'Чипси Lay`s картопляні зі смаком краба, 120г'
CHIPS_LAYS_SIR_60GR = 'Чіпси Lay`s картопляні зі смаком сиру, 60г'
SIR_SVET_FETA_UKR_ROZSIL_45_1KG = 'Сир Свет Сыр Фета Українська розсільний 45% в/у'
OLIVKI_EXTRA_CHORNI_BEZ_KIST_300GR = 'Оливки Extra! чорні без кісточки, 300г'
OLIV_OIL_POVNA_CHASHA_913GR = 'Масло оливковое Повна Чаша, 913г'
BASILIK_CHERVONIY_SVIJIY = 'Базілік червоний свіжий'
PELMENI_GERKULES_FIRM_400GR = 'Пельмени Геркулес Фирменные , 400г'
PELMENI_GERKULES_FIRM_800GR = 'Пельмени Геркулес Фирменные , 800г'
PELMENI_GERKULES_INDEYKA_400GR = 'Пельмени Геркулес с мясом индейки, 400г'
PELMENI_TRI_VEDMEDI_FIRM_800GR = 'Пельмени Три Ведмеді Фирменные, 800г'
PELMENI_TRI_VEDMEDI_MISHUTKA_TELYATINA_400GR = 'Пельмени Три ведмеді Мишутка телятина, 400г'
PELMENI_EXTRA_FIRM_800GR = 'Пельмени Extra! Фирменные, 800г'
PELMENI_EXTRA_SIBIR_500GR = 'Пельмени Extra! Сибирские, 500г'
PELMENI_EXTRA_RAVIOLI_DOMASHNIE_800GR = 'Равиоли Extra! Домашние, 800г'
SEVEN_UP_033JB = 'Напиток 7UP безалкогольный, сильногазированный, ж/б, 0,33л'
KAVUN = 'Кавун, кг'
JIVCHIK_APPLE_2l = 'Напиток Живчик яблоко 2 л'
JIVCHIK_APPLE_1l = 'Напиток Живчик яблоко 1 л'
JIVCHIK_APPLE_05l = 'Напиток Живчик яблоко 0.5 л'
JIVCHIK_GRUSHA_1l = 'Напиток Живчик груша 1 л'
JIVCHIK_SMART_COLA_2l = 'Живчик Smart Сola, 2л'
JIVCHIK_LIMON_2l = 'Живчик лімон, 2л'
JIVCHIK_SMART_COLA_1l = 'Живчик Smart Сola, 1 л'
BIOLA_STRAWBERRY_KIWI_2L = 'Біола полуниця-ківі, 2л'
BIOLA_LEMONAD_2L = 'Біола лімонад, 2л'
BON_BOISSON_LIMONAD_1L = 'Напиток Bon Boisson Лимонад, 1л'
BON_BOISSON_LIMONAD_2L = 'Напиток Bon Boisson Лимонад, 2л'
BON_BOISSON_LIME_MINT_2L = "Напиток Bon Boisson Лайм-м'ята, 2л"
BON_BOISSON_BAIKAL_2L = "Напиток Bon Boisson Байкал, 2л"
BON_BOISSON_TARHUN_2L = "Напиток Bon Boisson Тархун, 2л"
BON_BOISSON_BAIKAL_1L = "Напиток Bon Boisson Байкал, 1л"
BON_BOISSON_MULT_SOK_1L = "Напиток Bon Boisson Мультивитамин з натурал.соком, 1л"
BON_BOISSON_MANGO_2L = "Напиток Bon Boisson манго, 2л"
BON_BOISSON_MOHITO_2L = "Напиток Bon Boisson мохіто, 2л"
BON_BOISSON_SITRO_2L = "Напиток Bon Boisson сітро, 2л"
BON_BOISSON_KREM_SODA_2L = "Напиток Bon Boisson крем-сода, 2л"
BON_BOISSON_MULT_SOK_2L = "Напиток Bon Boisson Мультивитамин з натурал.соком, 2л"
MIRINDA_ORANGE_033JB = "Mirinda Апельсин 0.33л жб"
MIRINDA_ORANGE_05L = "Mirinda Апельсин 0.5л п/п"
SCHWEPPES_GRANAT_1L = "Напій Schweppes гранат 1 л"
SCHWEPPES_INDIAN_TONIC_033JB = "Напій Schweppes Indian Tonic 0.33 з/б"
SCHWEPPES_TANGERINE_033JB = "Напій Schweppes Tangerine 0.33 з/б"
SCHWEPPES_ORIGINAL_BITTER_LEMON_033JB = "Напій Schweppes Original bitter lemon 0.33 з/б"
SCHWEPPES_ORIGINAL_BITTER_LEMON_075pl = "Напій Schweppes Original bitter lemon 0.75 пл"
SCHWEPPES_ORIGINAL_BITTER_LEMON_1L = "Напій Schweppes Original bitter lemon 1 л"
SCHWEPPES_GRANAT_075L = "Напій Schweppes гранат 0.75 л"
SCHWEPPES_GRANAT_033JB = "Напій Schweppes гранат 0.33 л з/б"
SCHWEPPES_CLASSIC_MOJITO_033JB = "Напій Schweppes Classic Mojito 0.33 з/б"
FARSH_GOVYAJIY = "Фарш гов'яжий, кг"
RICE_EXTRA_KRUGLIY_1KG = "Ріс круглий Extra! 1 кг"
MASLO_FERMA_SELYANSKE_73JIR_180GR = 'Масло сладкосливочное Ферма Сельское 73%, 180г'
MASLO_FERMA_CHOCOLAT_62JIR_180GR = 'Масло сладкосливочное Ферма Шоколадное с какао 62.5%, 180г'
MASLO_FERMA_EXTRA_82JIR_180GR = 'Масло сладкосливочное Ферма Екстра 82.5%, 180г'
MASLO_FERMA_BUTER_63JIR_180GR = 'Масло сладкосливочное Ферма Бутербродне 63%, 180г'
MASLO_FERMA_SELYANSKE_73JIR_400GR = 'Масло сладкосливочное Ферма Сельское 73%, 400г'
MASLO_JAGOTINSKE_EXTRA_82_5_180GR = 'Масло сладкосливочное Яготинське Экстра 82,5%, 180г'
MASLO_JAGOTINSKE_BUTER_69_2_200GR = 'Масло сливочное "Яготинське" бутербродне 69,2%, 200г'
MASLO_SELYANSKE_EXTRA_82_180GR = 'Масло Селянське солодковершкове экстра 82%, 180 г'
MASLO_SELYANSKE_BUTER_63_180GR = 'Масло Селянське сладкосливочное бутербродное 63%, 180 г'
MASLO_SELYANSKE_72_5_180GR = 'Масло Селянське 72.5%, 180 г'
MASLO_GLOBINO_EXTRA_82_500GR = 'Масло Глобино Экстра сладкосливочное 82%, 500г'
MASLO_GLOBINO_BEZLAKTOZ_82_180GR = 'Масло сладкосливочное Глобино безлактозное 82%, 180г'
MASLO_GALICHINA_82_5_180GR = 'Масло сладкосливочное Галичина 82,5%, 180г'
MASLO_GALICHINA_SELYANSKE_72_6_180GR = 'Масло сладкосливочное Галичина селянське 72.6%, 180г'
MASLO_MALOKIYA_EXTRA_82_180GR = 'Масло сладкосливочное Молокія Экстра 82%, 180г'
MASLO_FARM_FRESH_EXTRA_82_180GR = 'Масло Farm Fresh Екстра вершкове 82%, 180 г'
MASLO_FARM_FRESH_SELYANSKE_82_180GR = 'Масло Farm Fresh селянське вершкове 73%, 180 г'
MASLO_PRESIDENT_82_200GR = 'Масло President солодковершкове 82%, 200г'
MASLO_PRESIDENT_82_400GR = 'Масло President солодковершкове 82%, 400г'
MASLO_PRESIDENT_SOLONE_80_200GR = 'Масло President солодковершкове солоне 80%, 200г'
JACOBS_MONARCH_BANKA_95GR = 'Кава розчинна Jacobs Monarch натуральна сублімована с/б, 95г'
JACOBS_MONARCH_BANKA_190GR = 'Кава розчинна Jacobs Monarch натуральна сублімована с/б, 190г'
JACOBS_MONARCH_BANKA_200GR = 'Кава розчинна Jacobs Monarch натуральна сублімована с/б, 200г'
JACOBS_MONARCH_BANKA_100GR = 'Кава розчинна Jacobs Monarch натуральна сублімована с/б, 100г'
JACOBS_MONARCH_BANKA_50GR = 'Кава розчинна Jacobs Monarch натуральна сублімована с/б, 50г'
JACOBS_MONARCH_CLASSICO_PACK_225GR = 'Кава мелена Jacobs Monarch Classic 225 г'
JACOBS_BARISTA_STRONG_PACK_225GR = 'Кава мелена Jacobs Barista Strong 225 г'
JACOBS_KRONUNG_500GR = 'Кава мелена Jacobs Kronung 500 г'
JACOBS_MONARCH_CLASSICO_PACK_70GR = 'Кава мелена Jacobs Monarch Classic 70 г'
JACOBS_MONARCH_INTENSE_PACK_200GR = 'Кава мелена Jacobs Monarch Intense смажена 200 гр'
JACOBS_ESPRESSO_PACK_230GR = 'Кава мелена Jacobs Espresso 230 г'
JACOBS_BARISTA_CLASSIC_PACK_225GR = 'Кава мелена Jacobs Barista Classic 225 г'
JACOBS_MONARCH_INTENSE_PACK_400GR = 'Кава мелена Jacobs Monarch Intense смажена 400 гр'
JACOBS_MONARCH_CLASSICO_PACK_400GR = 'Кава мелена Jacobs Monarch Classic 400 г'
JACOBS_MONARCH_ROZCH_PACK_60GR = 'Кава 60г Jacobs Monarch розчинна сублімована'
JACOBS_MONARCH_ROZCH_PACK_425GR = 'Кава 425г Jacobs Monarch розчинна сублімована'
NESCAFE_GOLD_PACK_165_GR = 'Кава розчинна Nescafe Gold натуральна 165 г'
NESCAFE_GOLD_PACK_310_GR = 'Кава розчинна Nescafe Gold натуральна 310 г'
NESCAFE_CLASSIC_PACK_170_GR = 'Кава розчинна Nescafe Classic натуральна 170 г'
NESCAFE_GOLD_PACK_360_GR = 'Кава розчинна Nescafe Gold натуральна 360 г'
NESCAFE_CLASSIC_PACK_30_GR = 'Кава розчинна Nescafe Classic натуральна 30 г'
NESCAFE_GOLD_PACK_30_GR = 'Кава розчинна Nescafe Gold натуральна 30 г'
NESCAFE_GOLD_PACK_60_GR = 'Кава розчинна Nescafe GOLD натуральна 60 г'
NESCAFE_CLASSIC_PACK_300_GR = 'Кава розчинна Nescafe Classic натуральна 300 г'
NESCAFE_GOLD_PACK_260_GR = 'Кава розчинна Nescafe GOLD натуральна 260 г'
CARTE_NOIRE_PACK_140GR = 'Кава розчинна Carte Noire натуральна сублімована 140 г'
CARTE_NOIRE_PACK_70GR = 'Кава розчинна Carte Noire натуральна сублімована 70 г'
CARTE_NOIRE_CARAMEL_PACK_120GR = 'Кава розчинна Carte Noire Caramel натуральна сублімована 120 г'
CARTE_NOIRE_PACK_210GR = 'Кава розчинна Carte Noire натуральна сублімована 210 г'
CARTE_NOIRE_PACK_280GR = 'Кава розчинна Carte Noire натуральна сублімована 280 г'
AMBASSADOR_PREMIUM_PACK_50GR = 'Кава розчинна Ambassador Premium 50 г'
AMBASSADOR_PREMIUM_PACK_100GR = 'Кава розчинна Ambassador Premium 100 г'
AMBASSADOR_PREMIUM_PACK_250GR = 'Кава розчинна Ambassador Premium 250 г'
AMBASSADOR_PREMIUM_PACK_170GR = 'Кава розчинна Ambassador Premium 170 г'
AMBASSADOR_PREMIUM_PACK_400GR = 'Кава розчинна Ambassador Premium 400 г'
AMBASSADOR_PREMIUM_PACK_500GR = 'Кава розчинна Ambassador Premium 500 г'
AMBASSADOR_PREMIUM_JAR_GLASS_190GR = 'Кава розчинна Ambassador Premium в скляній банці 190 г'
CHORNA_CARTA_GOLD_200GR = 'Кава розчинна «Чорна карта» Gold 200 г'
CHORNA_CARTA_GOLD_100GR = 'Кава розчинна «Чорна карта» Gold 100 г'
TCHIBO_GOLD_SELECTION_GLASS_JAR_50GR = 'Кава Tchibo Gold Selection с/б 50 г у банці'
TCHIBO_GOLD_SELECTION_GLASS_JAR_100GR = 'Кава Tchibo Gold Selection с/б 100 г у банці'
TCHIBO_GOLD_SELECTION_GLASS_JAR_200GR = 'Кава Tchibo Gold Selection с/б 200 г у банці'
TCHIBO_EXCLUSIVE_GLASS_JAR_200GR = 'Кава Tchibo Exclusive с/б 200 г у банці'
AROMA_GOLD_ROZCH_DECAFF_GLASS_JAR_100GR = 'Кава Aroma Gold без кофеїну розчинна 100 г'
AROMA_GOLD_ROZCH_FREEZE_DRIED_GLASS_JAR_100GR = 'Кава Aroma Gold freeze-dried розчинна 100 г'
AROMA_GOLD_ROZCH_FREEZE_DRIED_GLASS_JAR_200GR = 'Кава Aroma Gold freeze-dried розчинна 200 г'
MACCOFFEE_ARABICA_ROZCH_PACK_120GR = 'Кава розчинна MacCoffee Arabica натуральна сублімована 120 г'
MAXWELL_HOUSE_INSTANT_MILD_BLEND_ROZCH_GLASS_JAR_100GR = 'Кава розчинна Maxwell House Instant Mild Blend 100 г'
MAXWELL_HOUSE_INSTANT_MILD_BLEND_ROZCH_GLASS_JAR_200GR = 'Кава розчинна Maxwell House Instant Mild Blend 200 г'
DALLMAYR_GOLD_ROZCH_GLASS_JAR_100GR = 'Кава розчинна Dallmayr Gold натуральна сублімована 100 г'
DALLMAYR_GOLD_ROZCH_GLASS_JAR_200GR = 'Кава розчинна Dallmayr Gold натуральна сублімована 200 г'
AROMA_PLATINUM_ROZCH_FREEZE_DRIED_GLASS_JAR_200GR = 'Кава Aroma Platinum freeze-dried розчинна 200 г'
AROMA_PLATINUM_ROZCH_FREEZE_DRIED_GLASS_JAR_100GR = 'Кава Aroma Platinum freeze-dried розчинна 100 г'
BEANIES_MINCE_PIE_ROZCH_GLASS_JAR_50GR = 'Кава розчинна Beanies Mince Pie с/б, 50г'
BEANIES_CRISTMAS_PUDDING_ROZCH_GLASS_JAR_50GR = 'Кава розчинна Beanies Cristmas Pudding с/б, 50г'
BEANIES_DOUBLE_CHOCOLATE_ROZCH_GLASS_JAR_50GR = 'Кава розчинна Beanies Double Chocolate с/б, 50г'
BEANIES_CINDER_TOFFEE_ROZCH_GLASS_JAR_50GR = 'Кава розчинна Beanies Cinder Toffee с/б, 50г'
BUSHIDO_KODO_ROZCH_GLASS_JAR_95GR = 'Кава розчинна Bushido Kodo с/б, 95г'
DAVIDOFF_RICH_AROMA_ROZCH_GLASS_JAR_100GR = 'Кава Davidoff Rich Aroma, 100г'
DAVIDOFF_FINE_AROMA_ROZCH_GLASS_JAR_100GR = 'Кава Davidoff Fich Aroma, 100г'
AHMAD_TEA_ENG_BREAKF_BLACK_PACK_100GR = 'Чай Ahmad tea «Англійський до сніданку» чорний лістовий 100 г'
AHMAD_TEA_GRAF_GREY_BLACK_PACK_100GR = 'Чай Ahmad tea «Граф Грей» чорний лістовий 100 г'
AHMAD_TEA_LONDON_BLACK_PACK_100GR = 'Чай Ahmad tea «Лондон» чорний лістовий 100 г'
AHMAD_TEA_ENG_N1_BLACK_PACK_100GR = 'Чай Ahmad tea «Англійський №1» чорний лістовий 100 г'
AHMAD_TEA_ENG_BREAKF_BLACK_PACK_200GR = 'Чай Ahmad tea «Англійський до сніданку» чорний лістовий 200 г'
AHMAD_TEA_GRAF_GREY_BLACK_PACK_200GR = 'Чай Ahmad tea «Граф Грей» 200 г чорний листовий'
AHMAD_TEA_LONDON_BLACK_PACK_100PK = 'Чай чорний Ahmad Tea «Лондон» байховий пакетований 100 шт'
AHMAD_TEA_GRAF_GREY_BLACK_PACK_40PK = 'Чай Ahmad tea «Граф Грей» чорний пакетований 40 шт'
AHMAD_TEA_LONDON_BLACK_PACK_25PK = 'Чай чорний Ahmad Tea «Лондон» байховий чорний пакетований 25 шт'
AHMAD_TEA_LAVANDA_BERGAMOT_BLACK_PACK_20PK = 'Чай чорний Ahmad tea з лавандою і бергамотом пакетований 20 шт'
AHMAD_TEA_ENG_BREAKF_BLACK_PACK_25PK = 'Чай Ahmad tea Англійський сніданок чорний пакетований 25 шт'
AHMAD_TEA_ENG_N1_BLACK_PACK_25PK = 'Чай Ahmad tea «Англійський» №1 чорний пакетований 25 шт'
AHMAD_TEA_GRAF_GREY_BLACK_PACK_25PK = 'Чай Ahmad tea «Граф Грей» чорний пакетований 25 шт'
AHMAD_TEA_LONDON_BLACK_PACK_40PK = 'Чай чорний Ahmad Tea «Лондон» байховий чорний пакетований 40 шт'
AHMAD_TEA_ENG_BREAKF_BLACK_PACK_40PK = 'Чай Ahmad tea Англійський сніданок чорний пакетований 40 шт'
AHMAD_TEA_ENG_N1_BLACK_PACK_40PK = 'Чай Ahmad tea «Англійський» №1 чорний пакетований 40 шт'
AHMAD_TEA_ENG_BREAKF_BLACK_PACK_100PK = 'Чай Ahmad tea Англійський сніданок чорний пакетований 100 шт'
AHMAD_TEA_GRAF_GREY_BLACK_PACK_100PK = 'Чай Ahmad tea «Граф Грей» чорний пакетований 100 шт'
LIPTON_YELLOW_LABEL_BLACK_PACK_25PK = 'Чай чорний Lipton Yellow Label пакетований 25 шт'
LIPTON_EARL_GRAY_BLACK_PACK_25PK = 'Чай чорний Lipton Earl Gray пакетований 25 шт'
LIPTON_ENG_BREAKFAST_BLACK_PACK_25PK = 'Чай чорний Lipton English Breakfast пакетований 25 шт'
LIPTON_GOLD_TEA_BLACK_PACK_25PK = '	Чай чорний Lipton Gold Tea чорний пакетований 25 шт'
LIPTON_EARL_GREY_ORANGE_BLACK_PACK_25PK = 'Чай чорний Lipton Earl Grey Orange пакетований 25 шт'
LIPTON_FOREST_FRUITS_BLACK_PACK_20PK = 'Чай чорний Lipton Forest Fruit з ароматом лісових ягід пакетований 20 шт'
LIPTON_INTENSE_BLACK_BLACK_PACK_25PK = 'Чай чорний Lipton Intense Black пакетований 25 шт'
LIPTON_PEACH_MANGO_BLACK_PACK_20PK = 'Чай чорний Lipton Peach & Mango пакетований 20 шт'
LIPTON_YELLOW_LABEL_BLACK_PACK_50PK = 'Чай чорний Lipton Yellow Label  пакетований 50 шт'
LIPTON_INTENSE_BLACK_BLACK_PACK_92PK = 'Чай чорний Lipton Intense Black пакетований 92 шт'
LIPTON_GOLD_TEA_BLACK_PACK_92PK = '	Чай чорний Lipton Gold Tea чорний пакетований 92 шт'
LIPTON_YELLOW_LABEL_BLACK_PACK_100PK = 'Чай чорний Lipton Yellow Label  пакетований 100 шт'
LIPTON_EARL_GREY_BLACK_PACK_50PK = 'Чай чорний Lipton Earl Grey пакетований 50 шт'
LIPTON_INTENSE_MINT_GREEN_PACK_20PK = 'Чай зелений Lipton Intense Mint пакетований 20 шт'
LIPTON_RASPBERRY_POMEGRANATE_GREEN_PACK_20PK = 'Чай зелений Lipton Raspberry&Pomegranate пакетований 20 шт'
LIPTON_CLASSIC_GREEN_PACK_25PK = 'Чай зелений Lipton Classic пакетований 25 шт'
BATIK_KOROLIVSKIY_STANDART_BLACK_PACK_25PK = 'Чай чорний Batik Королівський стандарт ф/п 25 шт'
BATIK_GOLD_EARL_GREY_BLACK_PACK_25PK = 'Чай чорний Batik Gold Ерл Грей з аромат бергамота пакетований 25 шт'
BATIK_CHORNIY_BARHAT_BLACK_PACK_25PK = 'Чай чорний Batik Чорний бархат купажований дрібний 25 шт'
BATIK_JAGIDNIY_CILYNOK_BLACK_PACK_25PK = 'Чай чорний Batik Ягідний цілунок купажований дрібн 25 шт'
BATIK_BADYORIY_LIMON_BLACK_PACK_25PK = 'Чай чорний Batik Бадьорий лимон купажований дрібн 25 шт'
BATIK_GOLD_CEYLON_VISOKOGIR_BLACK_PACK_25PK = 'Чай чорний Batik Gold цейлон високогірний дрібний 25 шт'
BATIK_BLACK_GRANUL_STANDART_STS_100GR = 'Чай чорний Batik гранули С.Т.С. 100 грам'
BATIK_KOROL_STD_BLACK_100GR = 'Чай чорний Batik Королівський стандарт 100 г'
BATIK_CHORNIY_BARHAT_BLACK_PACK_60PK = 'Чай чорний Batik Чорний бархат купажований дрібний 60 шт'
BATIK_KOROLIVSKIY_STANDART_BLACK_PACK_100PK = 'Чай чорний Batik Королівський стандарт ф/п 100 шт'
AKBAR_GOLD_BLACK_25PK = 'Чай чорний Akbar Gold, пакет 25 шт'
AKBAR_LIMON_LIME_TWIST_BLACK_20PK = 'Чай чорний Akbar Lemon&Lime Twist 20 шт'
AKBAR_PEACH_PASSION_PUNCH_BLACK_20PK = 'Чай чорний Akbar Peach&Passion Punch 20 шт'
AKBAR_STRAWBERRY_KIWI_BLACK_20PK = 'Чай зелений китайський Akbar Strawberry Kiwi, 20х1.5 г'
PICKWICK_ENGLISH_BLACK_20PK = 'Чай чорний Pickwick English 20 шт'
PICKWICK_MANGO_BLACK_20PK = 'Чай чорний Pickwick ароматизований зі шматочками манго 20 шт'
PICKWICK_FOREST_FRUIT_BLACK_20PK = 'Чай чорний Pickwick Forest Fruit 20 шт'
PICKWICK_EARL_GREY_BLACK_20PK = 'Чай чорний Pickwick Earl Grey з ароматом бергамота 20 шт'
PICKWICK_STRAWBERRY_BLACK_20PK = 'Чай чорний Pickwick Strawberry 20 шт'
PICKWICK_GREEN_PURE_GREEN_20PK = 'Чай зеленый Pickwick green 20 шт'
PICKWICK_MINT_GREEN_20PK = 'Чай зеленый Pickwick mint 20 шт'
PICKWICK_ROMASHKA_GREEN_20PK = 'Чай зеленый Pickwick ромашковий 20 шт'
PICKWICK_SPICY_CHAI_TRAV_15PK = "Чай трав'яний Pickwick Joy of Tea Ройбуш з прянощами 1,75г*15шт"
PICKWICK_ROMASHKA_TRAV_15PK = "Чай трав'яний Pickwick вітамінний ромашка 15 шт"
PICKWICK_IMBIR_PRYAN_TRAV_15PK = "Чай трав'яний Pickwick імбірно-пряний 15 шт"
PICKWICK_ENERGY_TRAV_15PK = "Чай трав'яний Pickwick energy 15 шт"
PICKWICK_IMMUNITY_TRAV_15PK = "Чай трав'яний Pickwick immunity 15 шт"
PICKWICK_EARL_GREY_CITRUS_TRAV_15PK = "Чай трав'яний Pickwick Earl Grey Citrus 15 шт"
PICKWICK_CITRUS_BUZINA_TRAV_20PK = "Чай фруктово-трав'яний Pickwick цитрус-бузина 20 шт"
PICKWICK_IMBIR_LEMON_LEMONGRASS_TRAV_20PK = "Чай фруктово-трав'яний Pickwick імбир-лемонграс 20 шт"
AZERCHAY_BERGAMOT_BLACK_25PK = "Чай чорний Azercay з ароматом бергамота середньолистовий 25 шт"
AZERCHAY_BUKET_BLACK_25PK = "Чай чорний Azercay Buket 25 шт"
AZERCHAY_CHEBREC_BLACK_30PK = "Чай чорний Azercay Chebrec 30 шт"
SIR_PLAV_KOMO_DRUZBA_40_75GR = "Сир плавлений «Комо» «Дружба» 40%"
SIR_PLAV_KOMO_VERSHKOVIY_40_75GR = "Сир плавлений «Комо» Вершковий 40%"
SIR_PLAV_KOMO_ZELEN_CHASNIK_40_75GR = "Сир плавлений «Комо» з зеленню та часником 40% 75 г"
SIR_PLAV_KOMO_CRAB_PAL_40_75GR = "Сир плавлений «Комо» з крабовими паличками 40% 75 г"
SIR_PLAV_KOMO_GRIB_40_75GR = "Сир плавлений «Комо» з грибами 40% 75 г"
MILK_JAGOTINSKE_2_6_PL_870GR = "Молоко пастеризоване «Яготинське» 2,6% 870 г"
MILK_JAGOTINSKE_3_2_PL_870GR = "Молоко пастеризоване «Яготинське» 3.2% 870 г"
MILK_JAGOTINSKE_1_PL_870GR = "Молоко пастеризоване «Яготинське» 1% 870 г"
MILK_JAGOTINSKE_PRYAJ_2_6_PL_870GR = "Молоко пряжене «Яготинське» 2,6% 870 г"
MILK_GALICHINA_UKR_2_5_PL_870GR = "Молоко «Галичина» «Українське» 2,5% 870 г"
MILK_PREMIYA_PITNE_2_5_PL_900GR = "Молоко «Премія»® питне пастеризоване 2,5% 900 г"
MILK_PREMIYA_LOKO_PITNE_2_5_PL_900GR = "Молоко «Премія»® LOKO питне пастеризоване 2,5% 900 г"
MILK_PREMIYA_LOKO_PITNE_2_5_PL_2L = "Молоко «Премія»® LOKO питне пастеризоване 2,5% 2 л"
MILK_PREMIYA_LOKO_PITNE_3_2_PL_2L = "Молоко «Премія»® LOKO питне пастеризоване 3.2% 2 л"
MILK_ORGANIC_MILK_3_5_1L = "Молоко пастеризоване Organic Milk органічне 3,5% 1 л"
MILK_ORGANIC_MILK_2_5_470GR = "Молоко пастеризоване Organic Milk органічне 2,5% 470 г"
MILK_ORGANIC_MILK_2_5_1L = "Молоко пастеризоване Organic Milk органічне 2,5 % 1 л"
MILK_ORGANIC_MILK_BEZLAKTOZ_2_5_1L = "Молоко пастеризоване Organic Milk безлактозне органічне 2,5 % 1 л"
MILK_ORGANIC_MILK_0_5_1L = "Молоко пастеризоване Organic Milk органічне 0,5% 1 л"
MILK_PROSTONASHE_2_5_870GR = "Молоко пастеризоване Простонаше 2,5 % пл 870 г"
MILK_PROSTONASHE_PRYAJ_2_5_870GR = "Молоко пастеризоване Простонаше пряжене 2,5% пл 870 г"
MILK_PROSTONASHE_1_870GR = "Молоко пастеризоване Простонаше 1 % пл 870 г"
MILK_FERMA_2_5_PL_840GR = "Молоко пастеризоване «Ферма» 2,5 % 840 г"
MILK_FERMA_3_2_PL_840GR = "Молоко пастеризоване «Ферма» 3.2 % 840 г"
MILK_STRIY_PORICK_3_6_PL_1L = "Молоко пастеризоване «Лавка Традицій» «Старий Порицьк» органічне 3,6% 1 л"
MILK_STRIY_PORICK_PRYAJ_4_PL_1L = "Молоко пряжене «Лавка Традицій» «Старий Порицьк» органічне 4% 1 л"
MILK_STRIY_PORICK_2_5_PL_1L = "Молоко пастеризоване «Лавка Традицій» «Старий Порицьк» органічне 2.5% 1 л"
MILK_MOLOKIYA_2_5_PL_870GR = "Молоко пастеризоване Молокія 2,5% пл 870 г"
MILK_VOLOSHKOVE_POLE_2_5_PL_900GR = "Молоко пастеризоване «Волошкове поле» 2,5% 900 г"
MILK_GMZ_2_5_PL_1L = "Молоко пастеризоване ГМЗ №1 2,6% 1 л"
MILK_GMZ_4_pryaj_PL_1L = "Молоко пастеризоване пряжене ГМЗ №1 4% 1 л"
MILK_KOZ_ZOLOTA_KOZA_3_8_PL_500GR = "Молоко козяче пастеризоване «Лавка традицій» «Золота Коза» 3,8% 0.5 л"
MILK_KOZ_VIRTUOSO_BY_LUK_3_8_PL_500GR = "Молоко козине Virtuoso by Lukachivka незбиране 3% 0.5 л"
MILK_SVOE_3_4_PL_1L = "Молоко коров'яче «Своє», 3,4% 1 л"
MILK_OVEC_SOLOVIOV_LAKON_3_8_6_250GR = "Молоко «Лавка традицій» Soloviov овець породи Лакон 3,8-6% 250 гр"
MILK_SELYANSKE_OSOBL_2_5_PAP_PAK_950GR = "Молоко ультрапастеризоване «Селянське» особливе 2,5% 950 г"
MILK_SELYANSKE_MICROF_PITNE_2_5_PAP_PAK_950GR = "Молоко пастеризоване «Селянське» мікрофільтроване питне 2.5% 950 г"
MILK_SELYANSKE_OSOBL_3_2_TP_950GR = "Молоко ультрапастеризоване «Селянське» 3,2 % т/п 950 г"
MILK_SELYANSKE_OSOBL_RODINNE_2_5_TP_1500GR = "Молоко ультрапастеризоване «Селянське» «Родинне» 2,5% 1.5 л"
MILK_SELYANSKE_OSOBL_RODINNE_2_5_TP_2000GR = "Молоко ультрапастеризоване «Селянське» «Родинне» 2,5% 2 л"
MILK_SELYANSKE_OSOBL_1_5_TP_950GR = "Молоко «Селянське» особливе 1,5% 950 г"
MILK_SELYANSKE_OSOBL_2_5_TP_500GR = "Молоко ультрапастеризоване «Селянське» особливе 2,5% 500 г"
MILK_SELYANSKE_OSOBL_KIDS_3_2_TP_950GR = "Молоко ультрапастеризоване «Селянське» «Малюкам» для дітей 3,2% 950 г"
MILK_SELYANSKE_MICROF_PITNE_3_4_3_8_TP_950GR = "Молоко пастеризоване «Селянське» мікрофільтроване питне 3.4 - 3.8% 950 г"
MILK_JAGOTINSKE_ULTRA_2_6_TP_950GR = "Молоко «Яготинське» ультрапастеризоване 2,6% 950 г"
MILK_JAGOTINSKE_VELIK_2_6_TP_2000GR = "Молоко «Яготинське» «Велике» 2,6% жиру 2 л"
MILK_JAGOTINSKE_VELIK_2_6_TP_1500GR = "Молоко «Яготинське» «Велике» 2,6% жиру 1.5 л"


#НАЗВАНИЯ БЛЮД
RED_BORSH = 'борщ украинский'
VARENIKI_KARTOSHKA = 'вареники с картошкой'
VARENIKI_KAPUSTA = 'вареники с капустой'
GRECHESKIY_SALAT = 'греческий салат'
GOLUBCI = 'голубци'
CLASSIK_PLOV_V_KAZANE_NA_PLITE_SVININA = 'классический плов в казане на плите со свининой'
COTLETI_PO_KIEVSKI = 'классические котлеты по-киевски из куринного филе на сковороде'