# Generated by Django 4.2.1 on 2023-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('dish_description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение блюда')),
            ],
            options={
                'verbose_name': 'Досутпные блюда',
                'verbose_name_plural': 'Досутпные блюда',
            },
        ),
    ]
