# Generated by Django 4.2.1 on 2023-06-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_availabledishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDishes2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(choices=[('BORSH', 'Борщ украинский'), ('VAR_K', 'Вареники с картошкой')], max_length=5)),
                ('dish_description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение блюда')),
            ],
            options={
                'verbose_name': 'Досутпные блюда',
                'verbose_name_plural': 'Досутпные блюда',
            },
        ),
    ]
