# Generated by Django 4.2.1 on 2023-06-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_availabledishes2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTextsStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('item_text_file', models.CharField(max_length=50, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Тексты для обучения RNN',
                'verbose_name_plural': 'Тексты для обучения RNN',
            },
        ),
    ]
